name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours for more frequent updates
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full commit history for stats

      - name: Generate snake visualization
        uses: Platane/snk@master
        id: snake-gen
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake.gif
            dist/snake-dark.svg
            dist/snake-vertical.svg
            dist/snake-3d.gif?angle=30
            dist/snake-calendar.png?calendar=true
          # Advanced customization
          gif_frames_per_step: 8
          gif_duration: 65
          color_snake: "#ff6b6b"
          snake_color_gradient: true
          snake_head_shape: "round"
          snake_tail_shape: "pointed"
          snake_segments: 15
          dot_size: 4
          circle_radius: 5
          palette: github
          start_date: ""  # All-time contributions
          end_date: ""    # Up to today
          layout: classic
          with_head: true
          with_tail: true
          with_glow: true
          glow_radius: 8
          with_animation: true
          animation_speed: 1.5
          with_eyes: true
          with_tongue: true
          with_grid: true
          grid_color: "#444444"
          gif_reverse: true
          gif_loop_count: 0  # Infinite loop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate statistics report
        run: |
          echo "## Contribution Statistics" > dist/stats.md
          echo "- $(date +'%Y-%m-%d %H:%M')" >> dist/stats.md
          echo "![Snake Animation](snake.gif)" >> dist/stats.md
          curl -s "https://github-contributions.vercel.app/api/v1/${{ github.repository_owner }}?format=json" | jq -r '
            "Total Contributions: \(.total.contributions)",
            "Longest Streak: \(.streaks.longest.days) days (\(.streaks.longest.start} to \(.streaks.longest.end}))",
            "Current Streak: \(.streaks.current.days) days",
            "Daily Average: \(.averages.daily)",
            "Most Productive Day: \(.mostProductive.day) (\(.mostProductive.count) contributions)"
          ' >> dist/stats.md

      - name: Add repository metrics
        run: |
          echo "" >> dist/stats.md
          echo "### Repository Metrics" >> dist/stats.md
          echo "- Stars: $(curl -s https://api.github.com/repos/${{ github.repository }} | jq '.stargazers_count')" >> dist/stats.md
          echo "- Forks: $(curl -s https://api.github.com/repos/${{ github.repository }} | jq '.forks_count')" >> dist/stats.md
          echo "- Open Issues: $(curl -s https://api.github.com/repos/${{ github.repository }} | jq '.open_issues_count')" >> dist/stats.md

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "🐍 Updated snake - $(date +'%Y-%m-%d %H:%M')"
          force_orphan: true  # Keep branch history clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
